version: '3'

services:
  nodejs:
    build:
      context: ./socketio_example
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email maria.husmann@gmail.com --agree-tos --no-eff-email --staging -d chat.mariahusmann.ch  
volumes:
  certbot-etc:
  certbot-var:
  web-root: 


networks:
  app-network:
    driver: bridge    
